version: '3.8'

services:
  storybook:
    image: mcr.microsoft.com/playwright:v1.50.1
    environment:
      - NODE_ENV=development
      - TEST_PROJECT=storybook
      - CI=true
    volumes:
      - .:/app
      # Exclude node_modules to prevent platform-specific issues
      - /app/node_modules
      - /app/packages/*/node_modules
    working_dir: /app
    command: >
      bash -c "
        npm install -g pnpm@9.15.5 &&
        pnpm install --force &&
        pnpm build-storybook &&
        pnpm test:e2e:run --project=storybook --update-snapshots
      "
