name: Publish create-et-app Package

on:
  workflow_dispatch:

# Add these permissions
permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: .
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: packages/create-et-app
        run: pnpm build

      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Bump version manually
        working-directory: packages/create-et-app
        run: |
          # Bump the version without creating a git commit or tag
          pnpm version minor --no-git-tag-version

          # Stage the package.json change
          git add package.json

          # Retrieve the new version from package.json
          VERSION=$(node -p "require('./package.json').version")

          # Create a commit with the new version
          git commit -m "chore: bump version to ${VERSION} [skip ci]"

          # Create a corresponding git tag
          git tag "v${VERSION}"

          # Export the version to the GitHub environment for later steps (if needed)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Push changes
        run: |
          git push origin HEAD:main
          git push origin --tags

      - name: Publish to NPM
        working-directory: packages/create-et-app
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
