name: Deploy to Trigger.dev (prod)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: 🚀 Deploy Trigger.dev
        id: deploy
        continue-on-error: true
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          TRIGGER_API_URL: https://trigger.perfux.dev
        run: |
          pnpm dlx trigger.dev@latest deploy --self-hosted --load-image --registry docker.io --namespace eugen1993
          if [ $? -ne 0 ]; then
            echo "=== Build Failed - Error Log ==="
            cat /tmp/trigger-*/build-*.log 2>/dev/null || echo "No log file found"
            echo "============================="
            exit 1
          fi
