name: Deploy to Trigger.dev (prod)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: 🚀 Deploy Trigger.dev
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          TRIGGER_API_URL: https://trigger.perfux.dev
        run: |
          pnpm dlx trigger.dev@latest deploy --self-hosted --load-image --registry docker.io --namespace eugen1993

      - name: Display Build Logs
        if: always()
        run: |
          if [ -f "/tmp/trigger-*/build-*.log" ]; then
            echo "=== Build Log Contents ==="
            cat /tmp/trigger-*/build-*.log
            echo "======================="
          else
            echo "Build log file not found"
          fi

      - name: Check Build Status
        if: steps.deploy.outcome == 'failure'
        run: |
          echo "Build/Push step failed"
          exit 1
